//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_management.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderMapTables = new HashSet<OrderMapTable>();
        }
    
        public int Productid { get; set; }
        public string ProductName { get; set; }
        public int ProductCount { get; set; }
        public double ProductPrice { get; set; }
        public int CatId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMapTable> OrderMapTables { get; set; }
    }

    public class CartItem
    {
        public int Id { get; set; } // Product ID
        public string Name { get; set; } // Product Name
        public int Quantity { get; set; } // Quantity of the product in the cart
    }

}
